sudo: required
services:
  - docker
script:
  - export COMMIT_SHORT=$(git rev-parse --short HEAD)
  - docker build -t $DOCKER_IMG_NAME:$COMMIT_SHORT .
before_deploy:
  openssl aes-256-cbc -K $encrypted_0ff9a783091d_key -iv $encrypted_0ff9a783091d_iv -in travis/di-dep-ci.key.pem.enc -out travis/di-dep-ci.key.pem -d
deploy:
  - provider: script
    skip_cleanup: true
    script: travis/deploy.sh
    on:
      branch: initial
env:
  global:
    - DOCKER_IMG_NAME=navikt/di-dep-kafka-connect
    - GITHUB_APP_ID=29518
    # DOCKER_USERNAME
    - secure: "eeO/UavFfNKgGtu+GFvpz4yVVxtP+a8HCJTkmzIblD2g0z4IKyvmCje1WD0bJDwjiP9t0ld218OlaSGsKpwN+110Zif0KpbdERddxjKpSk2eb/1VntwLPYalWatgKIbtfy+zdPCJJj9bhGh6wATVhB5NnLK+mGWi3B0RVk3yir0qmcJuwl/+rPV5QFI35ucBchPuwiz7y4/wZZBddPV656y+3BK3cEYTLfknU7inAqVyJRTJ6mbi9LNGxnm4ELaWMVbqaxKsVg1+n3+/T1OEkuNUMXQuNR3edVmkft6O+qu87Ifg++xBciei1e5OhoiGWWvq5vNG41K0HJII6D/+9idUWWkyZZMYGeJLG7ZZlPzXrOAik9b77QYh8tJbfaz6BGHVSzAiHeeN5tvYPS4+lXB02wX9b+mJGa6yU9SLUKZnSQbUNvIVrCCmtsSpRcqiccF+s0i5wKe5LQOKCAshXiycKgfkrVC7VBOZ+I4vMcROcEmnNVeLpSXXrWtxcKqd9nDK1+7mTH4vQqGGavDI0BVTGpvXmeBe7x131l7XTy/Pg5DpfmO7KeqTCqlGKEhG7DVJPQrfXkzP5JaOMnRhafhpYCL0u51KesfTVA+JufK08zDMxJmC71TVgoaNhewfNBCljSVglt2VFp2ULUcJe3iZpBgo9mqLzjmPxaec8yg="
    # DOCKER_PASSWORD
    - secure: "w1OSgFlaVK/3p77JtHqcokUuvNITSd6eJobFwWSPYMJY/E8Sht41lpobH3/Di+l4dvrwBXJtWtSz+pAfss9RdMguT+ZjXZ8PxJvtgdLlgk4xr5uivaRp0zwCTQmp3ilKJlHRZ/c7jmupyGxr6+i2F4kLWxKjge2KAbvvZarLkcXUndyGs/R4hnbU/gnLVmvBSWsZzabcaxnZ4m4N38pOnGmb6tiFDQ2j+03xbzp0joS7ElrxE79iFYqmHhfj00DkK145GMtBTaAkgqXXyLX7U1LUlYL5lfB4Aizkvz9GalPuV1w0B4mM9krrz5EzhzOSk8fTKikNdRfBPRPhz6je/2VfFOx3aEdl5zLffUkZhTwE+JFQf7HejrmjP0SSNgg4O3vGmpP7U8LHJLjXsbrCpaqZPh65NdIWeiQeu6UGLRTP386scPpxkK0b/E7BaVtQLHOw0IG0Sl05ByElxPHxVipn3BqErP7YYJw7jCsvdm+8qLyRc+w3xXKI6MEq6ZzysPTYbor9KFINrHdtlVrWb6SGiZf7QlGyC78R+/cwLF5VS0CBYFSOZDlkyQaqfOfOe6oDM5RyRWLBQ6NR6u02HIA341QkeFox7WDS5IxjY/KuqcA0qRdiFyqAZg8BM1hBLpZw2ohnKTE1X5DiWgjX4DkD3ZgyMNmAVLp6wFIlf+g="
