apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: di-dep-kafka-connect
  namespace: default
  labels:
    team: di_dep
spec:
  image: comesfromci
  port: 8083
  resources:
    limits:
      cpu: 1000m
      memory: 3072Mi
    requests:
      cpu: 500m
      memory: 3072Mi
  vault:
    enabled: true
  liveness:
    path: "/"
    port: 8083
    initialDelay: 120
  ingresses:
    - "https://di-dep-kafka-connect.nais.preprod.local"
  replicas:
    min: 1
    max: 1
  env:
    - name: CONNECT_REST_PORT
      value: "8084"
    - name: CONNECT_GROUP_ID
      value: "di-dep-kafka-connect"
    - name: KAFKA_TOPIC_PREFIX
      value: "di-dep-connect"
    - name: CONNECT_KEY_CONVERTER
      value: "io.confluent.connect.avro.AvroConverter"
    - name: CONNECT_VALUE_CONVERTER
      value: "io.confluent.connect.avro.AvroConverter"
    - name: CONNECT_INTERNAL_KEY_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONNECT_INTERNAL_VALUE_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONNECT_REST_ADVERTISED_HOST_NAME
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: CONNECT_SECURITY_PROTOCOL
      value: "SASL_SSL"
    - name: CONNECT_SASL_MECHANISM
      value: "PLAIN"
    - name: CONNECT_CONSUMER_SECURITY_PROTOCOL
      value: "SASL_SSL"
    - name: CONNECT_CONSUMER_SASL_MECHANISM
      value: "PLAIN"
    - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
      value: "SASL_SSL"
    - name: CONNECT_PRODUCER_SASL_MECHANISM
      value: "PLAIN"
    - name: CONNECT_PLUGIN_PATH
      value: "/usr/share/java"
