#!/usr/bin/env bash

export CONNECT_SSL_TRUSTSTORE_LOCATION=$NAV_TRUSTSTORE_PATH
export CONNECT_SSL_TRUSTSTORE_PASSWORD=$NAV_TRUSTSTORE_PASSWORD
export CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION=$NAV_TRUSTSTORE_PATH
export CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD=$NAV_TRUSTSTORE_PASSWORD
export CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION=$NAV_TRUSTSTORE_PATH
export CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD=$NAV_TRUSTSTORE_PASSWORD
export CONNECT_SERVICEUSER_USERNAME=$(cat /secrets/serviceuser/srvNadaConnect/username)
export CONNECT_SERVICEUSER_PASSWORD=$(cat /secrets/serviceuser/srvNadaConnect/password)
export SCHEMA_REGISTRY=$(cat /var/run/secrets/nais.io/vault/schema.registry)

export CONNECT_BOOTSTRAP_SERVERS=$(cat /var/run/secrets/nais.io/vault/bootstrap.servers)
export CONNECT_SASL_JAAS_CONFIG="org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$CONNECT_SERVICEUSER_USERNAME\" password=\"$CONNECT_SERVICEUSER_PASSWORD\";"
export CONNECT_CONSUMER_SASL_JAAS_CONFIG=$CONNECT_SASL_JAAS_CONFIG
export CONNECT_PRODUCER_SASL_JAAS_CONFIG=$CONNECT_SASL_JAAS_CONFIG

export CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY
export CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY

export CONNECT_CONFIG_STORAGE_TOPIC=${KAFKA_TOPIC_PREFIX}-configs
export CONNECT_OFFSET_STORAGE_TOPIC=${KAFKA_TOPIC_PREFIX}-offsets
export CONNECT_STATUS_STORAGE_TOPIC=${KAFKA_TOPIC_PREFIX}-status
export CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY=Principal
export CONNECT_CONFIG_PROVIDERS=vault
export CONNECT_CONFIG_PROVIDERS_VAULT_CLASS=no.nav.kafkaconnect.VaultConfigProvider

exec bash -c "{ /etc/confluent/docker/run & nginx -g 'daemon off;' & /usr/local/bin/run-jmx-prometheus.sh; }"
