#!/usr/bin/env bash

NAV_TRUSTSTORE_PASSWORD=$(cat /var/run/secrets/nais.io/vault/truststore.password)

export CONNECT_SSL_TRUSTSTORE_LOCATION=$NAV_TRUSTSTORE_PATH
export CONNECT_SSL_TRUSTSTORE_PASSWORD=$NAV_TRUSTSTORE_PASSWORD
export CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION=$NAV_TRUSTSTORE_PATH
export CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD=$NAV_TRUSTSTORE_PASSWORD
export CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION=$NAV_TRUSTSTORE_PATH
export CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD=$NAV_TRUSTSTORE_PASSWORD

SCHEMA_REGISTRY=$(cat /var/run/secrets/nais.io/vault/schema.registry)

export CONNECT_BOOTSTRAP_SERVERS=$(cat /var/run/secrets/nais.io/vault/bootstrap.servers)
export CONNECT_SASL_JAAS_CONFIG=$(cat /var/run/secrets/nais.io/vault/sasl.jaas.config)
export CONNECT_CONSUMER_SASL_JAAS_CONFIG=$CONNECT_SASL_JAAS_CONFIG
export CONNECT_PRODUCER_SASL_JAAS_CONFIG=$CONNECT_SASL_JAAS_CONFIG

export CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY
export CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY

export CONNECT_CONFIG_STORAGE_TOPIC=${KAFKA_TOPIC_PREFIX}-configs
export CONNECT_OFFSET_STORAGE_TOPIC=${KAFKA_TOPIC_PREFIX}-offsets
export CONNECT_STATUS_STORAGE_TOPIC=${KAFKA_TOPIC_PREFIX}-status

exec bash -c "{ /etc/confluent/docker/run & nginx -g 'daemon off;'; }"
