#!/usr/bin/env bash

export CONNECT_SSL_TRUSTSTORE_LOCATION=$NAV_TRUSTSTORE_PATH
export CONNECT_SSL_TRUSTSTORE_PASSWORD=$NAV_TRUSTSTORE_PASSWORD
export CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION=$NAV_TRUSTSTORE_PATH
export CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD=$NAV_TRUSTSTORE_PASSWORD
export CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION=$NAV_TRUSTSTORE_PATH
export CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD=$NAV_TRUSTSTORE_PASSWORD

SCHEMA_REGISTRY=$(cat /var/run/secrets/nais.io/vault/schema.registry)
TOPIC_PREFIX=$(cat /var/run/secrets/nais.io/vault/topic.prefix)

export CONNECT_BOOTSTRAP_SERVERS=$(cat /var/run/secrets/nais.io/vault/bootstrap.servers)
export CONNECT_SASL_JAAS_CONFIG=$(cat /var/run/secrets/nais.io/vault/sasl.jaas.config)
export CONNECT_CONSUMER_SASL_JAAS_CONFIG=$CONNECT_SASL_JAAS_CONFIG
export CONNECT_PRODUCER_SASL_JAAS_CONFIG=$CONNECT_SASL_JAAS_CONFIG

export CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY
export CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=$SCHEMA_REGISTRY

export CONNECT_CONFIG_STORAGE_TOPIC=${TOPIC_PREFIX}-config
export CONNECT_OFFSET_STORAGE_TOPIC=${TOPIC_PREFIX}-offset
export CONNECT_STATUS_STORAGE_TOPIC=${TOPIC_PREFIX}-status

exec /etc/confluent/docker/run
