apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nada-kafka-connect-ui
  namespace: dataplattform
  labels:
    team: dataplattform
spec:
  image: landoop/kafka-connect-ui:0.9.7
  port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: "/"
    port: 8000
    initialDelay: 120
  ingresses:
    - "https://nada-kafka-connect-ui.nais.adeo.no"
    - "https://nada-kafka-connect-ui.prod-fss.nais.io"
  replicas:
    min: 1
    max: 2
  env:
    - name: CONNECT_URL
      value: "https://nada-kafka-connect.prod-fss.nais.io"
