apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nada-kafka-connect
  namespace: default
  labels:
    team: dataplattform
spec:
  image: {{ image }}
  port: 8083
  vault:
    enabled: true
  prometheus:
    enabled: true
    port: "5556"
    path: /
  liveness:
    path: /
    port: 8084
    initialDelaySeconds: 150
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
  readiness:
    path: /
    port: 8084
    initialDelaySeconds: 150
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
  resources:
    limits:
      cpu: 2000m
      memory: 3072Mi
    requests:
      cpu: 1000m
      memory: 2048Mi
  ingresses:
    - "https://nada-kafka-connect.nais.preprod.local"
  env:
    - name: CONNECT_REST_PORT
      value: "8084"
    - name: CONNECT_GROUP_ID
      value: "di-dep-kafka-connect-group"
    - name: KAFKA_TOPIC_PREFIX
      value: "di-dep-connect"
    - name: CONNECT_KEY_CONVERTER
      value: "io.confluent.connect.avro.AvroConverter"
    - name: CONNECT_VALUE_CONVERTER
      value: "io.confluent.connect.avro.AvroConverter"
    - name: CONNECT_INTERNAL_KEY_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONNECT_INTERNAL_VALUE_CONVERTER
      value: "org.apache.kafka.connect.json.JsonConverter"
    - name: CONNECT_REST_ADVERTISED_HOST_NAME
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: CONNECT_SECURITY_PROTOCOL
      value: "SASL_SSL"
    - name: CONNECT_SASL_MECHANISM
      value: "PLAIN"
    - name: CONNECT_CONSUMER_SECURITY_PROTOCOL
      value: "SASL_SSL"
    - name: CONNECT_CONSUMER_SASL_MECHANISM
      value: "PLAIN"
    - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
      value: "SASL_SSL"
    - name: CONNECT_PRODUCER_SASL_MECHANISM
      value: "PLAIN"
    - name: CONNECT_PLUGIN_PATH
      value: "/usr/share/java"
    - name: KAFKA_JMX_PORT
      value: "5555"
    - name: KAFKA_JMX_HOSTNAME
      value: "localhost"
    - name: NAV_TRUSTSTORE_PATH
      value: "/etc/ssl/certs/java/cacerts"
