name: build

on:
  push:
    branches:
      - master

env:
  BASEIMAGE: docker.pkg.github.com/${{ github.repository }}/nada-kafka-connect

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Declare image ref
        id: declare
        run: echo "::set-output name=image::${BASEIMAGE}:$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
    outputs:
      image: "${{ steps.declare.outputs.image }}"
  build:
    name: Build Connect
    needs:
      - setup
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login to Github Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build Docker
        run: docker build -t $IMAGE .
      - name: Push docker image
        run: docker push $IMAGE
  deploydev:
    name: Deploy Connect to Dev
    needs:
      - setup
      - build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/nais-dev.yaml
  deployuidev:
    name: Deploy Connect UI to Dev
    needs:
      - setup
      - deploydev
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/kafkaconnectui-dev.yaml
  deployprod:
    name: Deploy Connect to Prod
    needs:
      - setup
      - build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/nais-prod.yaml
  deployuiprod:
    name: Deploy Connect UI to Prod
    needs:
      - setup
      - deployprod
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/kafkaconnectui-prod.yaml
