name: build

on:
  - push
  - pull_request

env:
  BASEIMAGE: docker.pkg.github.com/${{ github.repository }}/nada-kafka-connect

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Declare outputs
        id: declare
        run: |
          echo "::set-output name=image::${BASEIMAGE}:$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
          echo "::set-output name=do_deploy::${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
    outputs:
      image: "${{ steps.declare.outputs.image }}"
      do_deploy: "${{ steps.declare.outputs.do_deploy }}"
  build:
    name: Build Connect
    needs:
      - setup
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login to Github Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build Docker
        run: docker build -t $IMAGE .
      - name: Push docker image
        run: docker push $IMAGE
        if: needs.setup.outputs.do_deploy == 'true'
  deploydev:
    name: Deploy to Dev
    needs:
      - setup
      - build
    if: needs.setup.outputs.do_deploy == 'true'
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/kafkaconnect.yaml,nais/kafkaconnectui.yaml
          VARS: nais/dev-vars.yaml
  deployprod:
    name: Deploy to Prod
    needs:
      - setup
      - build
    if: needs.setup.outputs.do_deploy == 'true'
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/kafkaconnect.yaml,nais/kafkaconnectui.yaml
          VARS: nais/prod-vars.yaml
